name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with Google Cloud using a service account key
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/githubcoudrun/cloudrun:${{ github.sha }} .
      
      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloudrun \
            --image gcr.io/githubcoudrun/cloudrun:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated  # Adjust as needed for authentication requirements
