name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main  # Replace with your main branch name or other branch you want to trigger on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with Google Cloud using a service account key
      - name: Authenticate with GCR
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/your-project-id/image-name:${{ github.sha }} .

      # Authenticate Docker with GCR
      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker

      # Push the Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/your-project-id/image-name:${{ github.sha }}

      # Optional: Deploy the image to Google Kubernetes Engine (GKE) or other platforms
      # Example: Update deployment with the new image
      - name: Update Kubernetes Deployment
        run: |
          gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone --project your-project-id
          kubectl set image deployment/your-deployment-name your-container-name=gcr.io/your-project-id/image-name:${{ github.sha }}
